services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: sf58-php
    working_dir: /var/www/src
    command: sh -lc "php artisan reverb:start --host=0.0.0.0 --port=6001 --hostname=localhost & php-fpm -F"
    volumes:
      - ./src:/var/www/src
    depends_on:
      - mysql
      - redis
    ports:
      - "6001:6001"

  nginx:
    image: nginx:1.27-alpine
    container_name: sf58-nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/src
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: sf58-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: sf58
      MYSQL_USER: sf58
      MYSQL_PASSWORD: sf58pass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: sf58-redis
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    container_name: sf58-mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

  node:
    image: node:20-alpine
    container_name: sf58-node
    working_dir: /app
    volumes:
      - ./frontend/frontend:/app
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"   # стабильный HMR в Docker/Windows
      WATCHPACK_POLLING: "true"
    command: sh -lc "tail -f /dev/null"

volumes:
  dbdata:
